# This is a basic workflow to help you get started with Actions

name: Build Jar

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "1.19.2" branch
  push:
    branches: 
      - '1.19.2'
    paths:
      - '/src/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out Repository code
        uses: actions/checkout@v4        

      # Runs a single command using the runners shell
      - name: List files in the repository
        run: |
          ls -a ${{ github.workspace }}
          
      - name: upload build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Origins-TFL-fabric-1.19.2.jar
          path: src/**
      - run: echo "🍏 This job's status is ${{ job.status }}."

